/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VetGUI;

import Dialog.AddPetDrug;
import Dialog.AddingNewPet;
import Dialog.ChangeClinicName;
import Dialog.ConfirmSave;
import Dialog.DrugList;
import Dialog.EditPet;
import Dialog.ConfirmLoad;
import Model.Pet;
import Model.VetClinic;
import Utils.VetClinicCsvRW;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author ricky
 */
public class VetClinicMainMenu extends javax.swing.JFrame {
    
    //private variables
    private VetClinic vetClinic;
    private ArrayList<Pet> pets;
    private PetTableModel petTableModel;
    private ChangeClinicName changeClinicName;
    private EditPet editPet;
    private AddPetDrug addPetDrug;
    private DrugList showDrugs;
    private ConfirmSave confirmSave;
    private ConfirmLoad confirmLoad;
    private AddingNewPet addingNewPet;
    /**
     * Creates new form VetClinicMainMenu
     */
    public VetClinicMainMenu() {
        initComponents();
        
        pets = new ArrayList<>();
        petTableModel = new PetTableModel(pets);
        petsTable.setModel(petTableModel);
        
        changeClinicName = new ChangeClinicName(this, true);
        editPet = new EditPet(this, true);
        addPetDrug = new AddPetDrug(this, true);
        showDrugs = new DrugList(this, true);
        confirmSave = new ConfirmSave(this, true);
        confirmLoad = new ConfirmLoad(this, true);
        addingNewPet = new AddingNewPet(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        petsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_ChangeClinicName = new javax.swing.JButton();
        btn_AddPet = new javax.swing.JButton();
        btn_EditPet = new javax.swing.JButton();
        btn_DeletePet = new javax.swing.JButton();
        lbl_ClinicName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_SortID = new javax.swing.JButton();
        btn_sortDose = new javax.swing.JButton();
        btn_sortTypeAge = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        btn_LoadFile = new javax.swing.JButton();
        btn_SaveFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_addDrug = new javax.swing.JButton();
        btn_showDrugs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        petsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pet ID", "Name", "Weight", "Date of Birth", "Accumulated Dose", "Breed / Allergy"
            }
        ));
        jScrollPane1.setViewportView(petsTable);

        btn_ChangeClinicName.setText("Change Clinic Name");
        btn_ChangeClinicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeClinicNameActionPerformed(evt);
            }
        });

        btn_AddPet.setText("Add New Pet");
        btn_AddPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPetActionPerformed(evt);
            }
        });

        btn_EditPet.setText("Edit Selected Pet");
        btn_EditPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditPetActionPerformed(evt);
            }
        });

        btn_DeletePet.setText("Delete Selected Pet");
        btn_DeletePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletePetActionPerformed(evt);
            }
        });

        lbl_ClinicName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ClinicName.setText("New Vet Clinic");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pets Options :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Table Options :");

        btn_SortID.setText("Sort by Pet ID");
        btn_SortID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SortIDActionPerformed(evt);
            }
        });

        btn_sortDose.setText("Sort by Accumulated Dose");
        btn_sortDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortDoseActionPerformed(evt);
            }
        });

        btn_sortTypeAge.setText("Sort by Type then Age");
        btn_sortTypeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortTypeAgeActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_LoadFile.setText("Load Table from a File");
        btn_LoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadFileActionPerformed(evt);
            }
        });

        btn_SaveFile.setText("Save Table");
        btn_SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveFileActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Other Options:");

        btn_addDrug.setText("Add Drug to Selected Pet");
        btn_addDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addDrugActionPerformed(evt);
            }
        });

        btn_showDrugs.setText("Show Drug(s) for Selected Pet");
        btn_showDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showDrugsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ChangeClinicName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_AddPet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EditPet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DeletePet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_ClinicName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SortID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sortDose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sortTypeAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LoadFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SaveFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addDrug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_showDrugs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ClinicName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ChangeClinicName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AddPet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EditPet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_DeletePet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_showDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SortID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sortDose, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sortTypeAge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LoadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //done
    private void btn_ChangeClinicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeClinicNameActionPerformed
        changeClinicName.setVisible(true);
        String clinicName = changeClinicName.getChangedName();
        if(clinicName == null){
            JOptionPane.showMessageDialog(this, "Change Clinic Name Cancelled.");
        }
        else{
            lbl_ClinicName.setText(clinicName);
            JOptionPane.showMessageDialog(this, "Clinic name is successfully changed");
        }
    }//GEN-LAST:event_btn_ChangeClinicNameActionPerformed
    //done
    private void btn_sortTypeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortTypeAgeActionPerformed
        petTableModel.sortByTypeThenAge();
    }//GEN-LAST:event_btn_sortTypeAgeActionPerformed
    //done
    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_LoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadFileActionPerformed
//        confirmLoad.setVisible(true);
//        if(confirmLoad.getVetClinic().getClinicName().equals("")){
//            JOptionPane.showMessageDialog(this, "Load Cancelled");
//        }else{
//            petTableModel.setPets(confirmLoad.getVetClinic().getPets());
//            lbl_ClinicName.setText(confirmLoad.getVetClinic().getClinicName());
//        }
        JFileChooser jFileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jFileChooser.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File file = jFileChooser.getSelectedFile();
            //JOptionPane.showMessageDialog(this, file.getAbsolutePath());
            this.vetClinic = VetClinicCsvRW.readCsvFile(this, file.getAbsolutePath());
            lbl_ClinicName.setText(vetClinic.getClinicName());
            petTableModel.setPets(vetClinic.getPets());
        }

    }//GEN-LAST:event_btn_LoadFileActionPerformed

    private void btn_AddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPetActionPerformed
        
        addingNewPet.setVisible(true);
        if(addingNewPet.getAddAPet() == null){
            JOptionPane.showMessageDialog(this, "Pet addition cancelled.");
        }
        else{
            petTableModel.addPet(addingNewPet.getAddAPet());
        }
    }//GEN-LAST:event_btn_AddPetActionPerformed
    //done
    private void btn_sortDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortDoseActionPerformed
        petTableModel.sortPetAccumulatedDose();
    }//GEN-LAST:event_btn_sortDoseActionPerformed
    //done   
    private void btn_SortIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SortIDActionPerformed
        petTableModel.sortByID();
    }//GEN-LAST:event_btn_SortIDActionPerformed
    //done
    private void btn_DeletePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletePetActionPerformed
        int i = petsTable.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "No pet selected yet!");           
        }
        else{
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to delete this? ");
            if(dialogResult == JOptionPane.YES_OPTION){
                petTableModel.deletePet(i);
            }   
        }
        
    }//GEN-LAST:event_btn_DeletePetActionPerformed

    private void btn_EditPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditPetActionPerformed
        int i = petsTable.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "No pet selected yet!");           
        }
        else{
            editPet.setEditPet(petTableModel.getSelectedPet(i));
            editPet.setVisible(true);
            if(editPet.getDoneEditPet() != null){
                petTableModel.updatePet(editPet.getDoneEditPet());
                JOptionPane.showMessageDialog(this, "Pet Successfully updated!");
            }else{
                JOptionPane.showMessageDialog(this, "Pet is not updated!");
            }
        }
    }//GEN-LAST:event_btn_EditPetActionPerformed

    private void btn_SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveFileActionPerformed
        pets = petTableModel.getPets();
        vetClinic = new VetClinic(lbl_ClinicName.getText());
        vetClinic.setPets(pets);
        confirmSave.setVetClinic(vetClinic);
        confirmSave.setVisible(true);
        
        
    }//GEN-LAST:event_btn_SaveFileActionPerformed

    private void btn_addDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addDrugActionPerformed
        // TODO add your handling code here:
        //create add drug dialog
        // getpet from table
        //create dose with specs
        //date today date
        // check dose null or not
        // if not null pet add dose
        //last update to table
        int i = petsTable.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "No pet selected yet!");           
        }
        else{
            Pet pet = petTableModel.getSelectedPet(i);
            if (pet.getDose() == 0){
                JOptionPane.showMessageDialog(this, "Cant add another drug to this pet");
            }
            else{
                addPetDrug.setPet(pet);
                addPetDrug.setVisible(true); 
            }
            if(addPetDrug.getPet() == null && addPetDrug.getDose() == null){
                JOptionPane.showMessageDialog(this, "Drug addition cancelled.");
            }
            else{
                petTableModel.updatePet(addPetDrug.getPet());
                JOptionPane.showMessageDialog(this, "Drug added successfully");
            }
            addPetDrug.setPet(null);
            addPetDrug.setDose(null);
        }
        
        
    }//GEN-LAST:event_btn_addDrugActionPerformed

    private void btn_showDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showDrugsActionPerformed
        int i = petsTable.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "No pet selected yet!");           
        }
        else{
            Pet pet = petTableModel.getSelectedPet(i);
            showDrugs.setDoses(pet.getDoseList());
            if(pet.getDoseList().isEmpty()){
                JOptionPane.showMessageDialog(this, "No Drug is registered to this pet yet!");
            }
            else{
                showDrugs.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_showDrugsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetClinicMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetClinicMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetClinicMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetClinicMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetClinicMainMenu().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddPet;
    private javax.swing.JButton btn_ChangeClinicName;
    private javax.swing.JButton btn_DeletePet;
    private javax.swing.JButton btn_EditPet;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_LoadFile;
    private javax.swing.JButton btn_SaveFile;
    private javax.swing.JButton btn_SortID;
    private javax.swing.JButton btn_addDrug;
    private javax.swing.JButton btn_showDrugs;
    private javax.swing.JButton btn_sortDose;
    private javax.swing.JButton btn_sortTypeAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ClinicName;
    private javax.swing.JTable petsTable;
    // End of variables declaration//GEN-END:variables
}
